name:       double-ratchet
version:    0.1.0
synopsis:   A double ratchet implementation parameterized over your choice of KDFs
stability:  experimental
author:     Arjun Khandkar
copyright:  (c) 2026 Arjun Khandkar

language: GHC2021

default-extensions:
  - AllowAmbiguousTypes
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilies

dependencies:
  - base
  - containers
  - mtl
  - random
  - text
  - hspec
  - hedgehog

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors

library:
  source-dirs: src

  exposed-modules:
    DoubleRatchet.Class
    DoubleRatchet.RatchetM
    DoubleRatchet.RatchetState
    Test.TestMain

  other-modules:
    Test.Implementation
    Test.ToyCrypto

tests:
  state-machine-spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - double-ratchet
      - hspec
